version: '3'

services:
  catalog:
    build:
      context: ./catalog
    container_name: catalog
    environment:
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 18088
    ports:
      - "8082:8082"
    networks:
      - lab
  order-1:
    build:
      context: ./order
    container_name: order-1
    environment:
      CATALOG_HOST: catalog
      CATALOG_PORT: 8082
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 18088
      ORDER_HOSTS: '[{"id":2,"hostname":"order-2","port":8083}, {"id":3,"hostname":"order-3","port":8083}]'
      ID: 1
    ports:
      - "8083:8083"
    networks:
      - lab
  order-2:
    build:
      context: ./order
    container_name: order-2
    environment:
      CATALOG_HOST: catalog
      CATALOG_PORT: 8082
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 18088
      ORDER_HOSTS: '[{"id":1,"hostname":"order-1","port":8083}, {"id":3,"hostname":"order-3","port":8083}]'
      ID: 2
    ports:
      - "8084:8083"
    networks:
      - lab
  order-3:
    build:
      context: ./order
    container_name: order-3
    environment:
      CATALOG_HOST: catalog
      CATALOG_PORT: 8082
      FRONTEND_HOST: frontend
      FRONTEND_PORT: 18088
      ORDER_HOSTS: '[{"id":1,"hostname":"order-1","port":8083}, {"id":2,"hostname":"order-2","port":8083}]'
      ID: 3
    ports:
      - "8085:8083"
    networks:
      - lab
  frontend:
    build:
      context: ./frontend
    container_name: frontend
    environment:
      CATALOG_HOST: catalog
      CATALOG_PORT: 8082
      CACHING: 'true'
      ORDER_HOSTS: '[{"id":1,"hostname":"order-1","port":8083}, {"id":2,"hostname":"order-2","port":8083}, {"id":3,"hostname":"order-3","port":8083}]'
    ports:
      - "18088:18088"
    depends_on:
      - catalog
      - order-3
      - order-2
      - order-1
    networks:
      - lab
networks:
  lab:
